theme: jekyll-theme-minimal

title: PHYSHPC 2024 - Workshop in High-Performance Computing in Physics
logo: /assets/logo.png
conf_city: Madrid, Spain
acronym: PHYSHPC 2024
workshop_date: August 27, 2024
submission_deadline: May 6th, 2024 (AoE)
acceptance_notification: June 20th, 2024 (AoE)
revisions_of_accepted_papers_due: July 1st, 2024 (AoE)
